### ISSUE TITLE
Complete component information

### ISSUE THREAD

**Issue by ErinvanderVeen** [tweag/genealogos#2]
The components array of the cycloneDX v1.5 spec contains the information of all components in the sbom.

The information below relates both to `nixtract`

- [x] type (required) - Since nixpkgs does not expose this, all nixpkgs components are currently `application`s.
- [x] ~mime_type~ - impossible to determine without accessing the Nix store
- [x] bom_ref - the derivation's output path
- [x] ~supplier~ - data not present in nixpkgs
- [x] ~author~ - data not present in nixpkgs
- [x] ~publisher~ - data not present in nixpkgs
- [x] ~group~ - see publisher above
- [x] name (required) - the package name
- [x] version - the package version from the metadata
- [x] description - the package description from the metadata
- [x] ~scope~ - cannot be derived using nix eval, can be left empty for the default of "required"
- [x] ~hashes~ - might be doable for CA derivations, otherwise impossible without access to the nix store
- [x] licenses
- [x] ~copyright~ - data not present in nixpkgs
- [x] ~cpe~ - data not present in nixpkgs, but might be extractable from the official CPE dictionary
- [ ] ~purl~ - unachievable, the `nix` purl isn't standardized (yet) (https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#other-candidate-types-to-define)
- [x] ~swid - TBD, not present in nixpkgs, for exceptional packages maybe in the store~
- [x] ~modified~ - deprecated, should not be present
- [x] ~pedigree~ - maybe for later
- [x] external_references
- [x] ~components~ - not extractable from nixpkgs, we cannot derive this information
- [x] ~evidence~ - TBD, maybe when/if we perform more in-depth analysis
- [x] ~releaseNotes~ - based on the source, might be extractable from nixpkgs, low priority
- [x] ~modelCard~ - only applicable to components of type "machine-learning-model", which we don't produce yet
- [x] ~data~ - only applicable to components of type "data", which we don't produce yet
- [ ] properties - TBD: https://github.com/CycloneDX/cyclonedx-property-taxonomy
- [x] ~signature~ - if desired, official tools can be used to add a signature to Genealogos' output. Genealogos will not include signing capabilities.

**Comment by GuillaumeDesforges** [comment]
Should be enough for the first milestone
