### ISSUE TITLE
genealogos: get a CycloneDX SBOM from Nix via a browser

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/genealogos#21]
While the API is the first step to making SBOM from Nix available to everyone, we are convinced it should target an audience as broad as possible, beyond those who can use an HTTP API directly.

To that end, the web service should provide a UI that facilitates the process for everyone.

Deliverables:
* Release of a new version of genealogos that includes a browsable web service to generate a CycloneDX SBOM from a reference to a Nix flake 
* Guide on how to run the web server
* Documentation for the web interface
```[tasklist]
### Tasks
```

**Comment by ErinvanderVeen** [comment]
Resolved!
