### ISSUE TITLE
genealogos: write a NixOS module to self-host Genealogos

### ISSUE THREAD

**Issue by GuillaumeDesforges** [tweag/genealogos#23]
It should be easy to run your own Genealogos instance. Because we love NixOS, we want to provide a NixOS module so that deploying Genealogos should be as easy as add  services.genealogos.enable = true; to a NixOS configuration.

Deliverables:
* Nix code of a NixOS module in the source repository to run a Genealogos instance
* Documentation explaining how to use and configure the module
* Link to a GitHub Pull Request that submits the NixOS module to nixpkgs

**Comment by ErinvanderVeen** [comment]
Resolved with #48 and #49
