### ISSUE TITLE
Consider switching from serde_cyclonedx to cyclonedx-sbom

### ISSUE THREAD

**Issue by ErinvanderVeen** [tweag/genealogos#40]
Since we started this project, the official rust crate [cyclonex-sbom](https://crates.io/crates/cyclonedx-bom) for CycloneDX has gotten into a state where it is suitable for our purpose.

But there are some things to consider:
Advantages:
- Support for XML and JSON, see also #39 
- Code de-duplication, we currently need a lot of duplicate code to generate both 1.4 and 1.5, using this crate would resolve that issue.
- We can drop our dependency on some other crates as well

Disadvantages:
- The official crate has (as of yet) only support for 1.3 and 1.4, with the current newest standard being 1.5, however support for 1.5 is on the horizon with https://github.com/CycloneDX/cyclonedx-rust-cargo/issues/646.

**Comment by lfrancke** [comment]
Hi @ErinvanderVeen, thanks for considering `cyclonedx-bom`

Yes, CycloneDX 1.5 should be done soon-ish but latest at the end of April.
The work on this is [funded](https://www.sovereigntechfund.de/tech/rusty-sboms) by the German government and we have a deadline ;-)

Please reach out to us via GitHub, or the CycloneDX slack or me personally if you have any problems or feedback.
